fix the issue of not reading too long file.
mrombout/gdgettext pull request #4
Opened 2024-04-16 17:11 UTC by LoserFox

longer than 65565 bytes content will not be processed.

2024-04-16 18:51 UTC, LoserFox commented
although a bit offtopic, but i recommend `(?m)(?:text = "|[^s]tr\(["'])(.*?)(?:"|["']\))` change to `(?m)(?: = "|[^s]tr\(["'])(.*?)(?:"|["']\))` to get custom export variable support.

2024-05-06 17:19 UTC, mrombout requested changes
I tried extracting from a `709585` bytes on a build without this patch and it extracted without problem. But a streaming approach is indeed better than loading the entire file into memory as was done previously.

2024-05-06 17:19 UTC, mrombout commented on process.go
> +			panic(e)
I think it's better to keep the `panic()`s in the main and use plain errors throughout the code base.
```suggestion
			return poFile, err
```

2024-05-06 17:19 UTC, mrombout commented on process.go
> +		f, e := os.Open(filePath)
Revert to `err` to keep in line with standard go practices.

```suggestion
		f, err := os.Open(filePath)
```

2024-05-06 17:19 UTC, mrombout commented on process.go
> +		f, e := os.Open(filePath)
In order to keep the tests working, this `os.Open` call needs to go through the `fileSystem` interface and then be mocked.

Or better yet, these days it's probably better to rely on `fs.FS`.

2026-06-01 14:43 UTC, closed without merging